### PR TITLE
Ignore specific link targets

### LINKED ISSUE #1401: Add ability to ignore warnings
In some cases it might be desirable to manually approve a false positive. Especially when using a template like https://github.com/ory/meta/blob/master/templates/repository/common/CONTRIBUTING.md
As far as I could tell there is currently no way to ignore errors.
My suggestion would be a comment like

```md
<!-- text-run ignore linkTarget -->
Check out [ORY $PROJECT Discussions]($DISCUSSIONS). This is a great place for
...
```

that allows to disable checks by rule name (just like `// @ts-ignore ...` or others).

### PR DESCRIPTION
**Pull request by kevgo**
resolves #1401

### CODE REVIEW

**Comment by zepatrik** [comment]
Nice, when are you planning the next release? Or how can I use the current master? I got it working by using this in the package.json:
```json
{
  ...
  "scripts": {
    ...
    "text-run-build": "cd node_modules/text-runner && npm i && make build-all",
    "text-run": "./node_modules/text-runner/text-runner-cli/bin/text-run"
  },
  "devDependencies": {
    ...
    "text-runner": "git+https://github.com/kevgo/text-runner.git#63c31b3"
  }
}
```
but as you can imagine the build takes quite some time.

**Comment by kevgo** [comment]
Text-Runner 5.0.0 will be released today. I'm currently in the process of updating the dependencies. The Node.js ecosystem values progress and often pursues it quite recklessly, so around a dozen dependencies have new major versions. Makes one value the focus on long-term stability and reliability in the Go ecosystem.

Btw, nice hack to build Text-Runner manually for the time being!

**Comment by zepatrik** [comment]
The build takes about 1min in the CI, while the actual run is more like 1s :sweat_smile: but it works for now.
I feel like js libs are not putting as much thought into API design as go authors might, therefore a lot of breaking changes...

**Comment by kevgo** [comment]
Text-Runner 5.0 is out! I also bumped the version of the Text-Runner standard library modules from `0.0.13` to `0.1`. Please let me know if you run into other issues.

I see multiple reasons for the volatility in the JS ecosystem. Similar to PHP, there are millions of JS developers. In such a large crowd, 98% of all people are beginners. Beginners need a few iterations to find the right abstractions to expose complex functionality through simple and straightforward APIs. But JS is also a bit similar to the Ruby world in that it favors creativity and trying out a new idea even if it isn't fully engineered through, stable, and scalable yet. Both aspects together make the JS world the most innovative software ecosystem that I'm aware of right now. One needs to try out ten dopey ideas to arrive at one really good one. The Go world has a much higher percentage of "serious" backend developers who run real production systems and (rightfully) don't like surprises and breaking changes. Which makes it a much nicer experience than JS for building production-grade software and maintaining it over many years.

**Comment by zepatrik** [comment]
I had a PR out already before your comment :wink: https://github.com/ory/meta/pull/92
Everything looks good :+1: 

I follow your arguments, the scope of JS and go is definitely not that overlapped.

**Comment by kevgo** [comment]
Nice!!

**Pull request merged**
